## Deliverable 2. Create a Customer Travel Destinations Map.

In [19]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Narsaq,GL,60.9167,-46.0500,46.62,95,100,2.55,light rain
1,1,Madimba,TZ,-10.4000,40.3333,68.74,86,8,8.57,clear sky
2,2,Lompoc,US,34.6391,-120.4579,70.09,81,1,10.36,clear sky
3,3,Namibe,AO,-15.1961,12.1522,65.68,86,21,8.57,few clouds
4,4,New Norfolk,AU,-42.7826,147.0587,55.89,64,98,1.07,overcast clouds

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
max_temp= float(input("What is your maximum temperature criteria?"))
min_temp= float(input("What is your minimum temperature criteria?"))

What is your maximum temperature criteria?90
What is your minimum temperature criteria?70

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df= city_data_df.loc[(city_data_df['Max Temp']>= min_temp) & (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Lompoc,US,34.6391,-120.4579,70.09,81,1,10.36,clear sky
6,6,Georgetown,MY,5.4112,100.3354,89.55,68,20,1.99,few clouds
7,7,Mount Pleasant,US,32.7941,-79.8626,79.99,90,20,3.00,mist
8,8,Hambantota,LK,6.1241,81.1185,86.34,74,20,14.97,few clouds
9,9,Celestun,MX,20.8667,-90.4000,77.50,89,64,13.47,broken clouds

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

Unnamed: 0             0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df= preferred_cities_df.dropna()

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Lompoc,US,70.09,clear sky,34.6391,-120.4579,
6,Georgetown,MY,89.55,few clouds,5.4112,100.3354,
7,Mount Pleasant,US,79.99,mist,32.7941,-79.8626,
8,Hambantota,LK,86.34,few clouds,6.1241,81.1185,
9,Celestun,MX,77.50,broken clouds,20.8667,-90.4000,
11,Atuona,PF,77.68,clear sky,-9.8000,-139.0333,
13,Panzhihua,CN,85.50,clear sky,26.5851,101.7128,
15,Kapaa,US,84.18,scattered clouds,22.0752,-159.3190,
19,Kununurra,AU,85.98,few clouds,-15.7667,128.7333,
23,Marzuq,YE,81.16,scattered clouds,14.4000,46.4667,

In [12]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat}, {lng}"
    # 6d. Set up the base URL for the Google Places API to get JSON data.
    base_url ="https://maps.googleapis.com/maps/api/place/nearbysearch/json?"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params= params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    # Iterate through the DataFrame.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found...skipping")

Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping
Hotel not found...skipping

In [23]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(30)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Lompoc,US,70.09,clear sky,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
6,Georgetown,MY,89.55,few clouds,5.4112,100.3354,Cititel Penang
7,Mount Pleasant,US,79.99,mist,32.7941,-79.8626,Best Western Patriots Point
8,Hambantota,LK,86.34,few clouds,6.1241,81.1185,Bungalow 63
9,Celestun,MX,77.50,broken clouds,20.8667,-90.4000,Posada Lilia
11,Atuona,PF,77.68,clear sky,-9.8000,-139.0333,Villa Enata
13,Panzhihua,CN,85.50,clear sky,26.5851,101.7128,Electric Power Hotel
15,Kapaa,US,84.18,scattered clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
19,Kununurra,AU,85.98,few clouds,-15.7667,128.7333,Hotel Kununurra
24,Bilma,NE,89.08,clear sky,18.6853,12.9164,Expeditions Ténére voyages
26,Hilo,US,78.53,light rain,19.7297,-155.0900,Hilo Hawaiian Hotel
27,Tautira,PF,78.82,broken clouds,-17.7333,-149.1500,Pension Oaoa
32,Kalispell,US,74.66,smoke,48.1958,-114.3129,Red Lion Hotel Kalispell
37,Along,IN,89.53,overcast clouds,28.1667,94.7667,Hotel West
39,Butaritari,KI,81.21,moderate rain,3.0707,172.7902,Isles Sunset Lodge
41,Fort Nelson,CA,71.19,smoke,58.8053,-122.7002,The Fort Nelson Hotel
43,Praia Da Vitoria,PT,72.75,broken clouds,38.7333,-27.0667,Hotel Branco I
44,Port Blair,IN,82.26,light rain,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
48,Vaini,TO,75.36,few clouds,-21.2000,-175.2000,Keleti Beach Resort
51,Norman Wells,CA,86.04,smoke,65.2820,-126.8329,Heritage Hotel
53,Awbari,LY,82.40,clear sky,26.5921,12.7805,فندق أوباري
54,Kahului,US,83.46,scattered clouds,20.8947,-156.4700,Maui Seaside Hotel
57,Bathsheba,BB,81.21,few clouds,13.2167,-59.5167,Atlantis Hotel
59,Dauphin,CA,71.74,clear sky,51.1494,-100.0502,Canway Inn & Suites
60,Singaparna,ID,71.89,overcast clouds,-7.3515,108.1110,Wisma Dewi Hotel
61,Maumere,ID,84.81,broken clouds,-8.6199,122.2111,Sylvia Hotel
64,Djenne,ML,81.18,overcast clouds,13.9061,-4.5533,Hôtel Chez Baba
65,Komsomolskiy,UZ,83.62,scattered clouds,40.4272,71.7189,Ikathouse
72,Yellowknife,CA,81.12,smoke,62.4560,-114.3525,The Explorer Hotel
73,Xixiang,CN,85.30,broken clouds,35.1628,112.8650,Sanmao Hotel Hotel

In [24]:
# 8a. Create the output File (CSV)
output_data_file="WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [38]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description </dt><dd>{Current Description}</dd><dt><dd> and <dd><dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [40]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))